# Generated by Django 6.0.3 on 2026-05-12 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('FAKE', 'Fake'), ('REAL', 'Real')], max_length=10)),
                ('confidence', models.FloatField()),
                ('fake_probability', models.FloatField()),
                ('real_probability', models.FloatField()),
                ('unified_score', models.FloatField()),
                ('verdict', models.CharField(choices=[('FAKE', 'Fake'), ('REAL', 'Real')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='detector.article')),
            ],
        ),
        migrations.CreateModel(
            name='APIVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.BooleanField(default=False)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_verification', to='detector.classificationresult')),
            ],
        ),
        migrations.CreateModel(
            name='LIMEExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_scores', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lime_explanation', to='detector.classificationresult')),
            ],
        ),
        migrations.CreateModel(
            name='RSSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_sources', models.JSONField(blank=True, default=list)),
                ('rss_score', models.FloatField(default=0.0)),
                ('coverage', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rss_verification', to='detector.classificationresult')),
            ],
        ),
    ]
